version: "3.9"
services:
  admin-back:
    build: .
    ports:
      - 8000:3000
    image: admin-back
    # environment:
    #   # access these from .env
    #   # - DB_HOST=$DB_HOST 
    #   # - DB_PORT=$DB_PORT
    #   # - DB_DATABASE=$DB_DATABASE
    #   # - DB_USERNAME=$DB_USERNAME
    #   # - DB_PASSWORD=$DB_PASSWORD
    #   # - SECRET_KEY=$SECRET_KEY
    depends_on:
      - db
    # extra_hosts:
    #   # this is required for connecting to the MySQL server on the host
    #   - "host.docker.internal:host-gateway"  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullstack_api
      # MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql  
